/** 演示原型当前已接入的页面；其余菜单仍保留结构，但标记为「未完成」且不可进入。 */
export const INCOMPLETE_MENU_TAG = '未完成';

export const IMPLEMENTED_PAGE_IDS = new Set([
  'warehouse-physical',
  'warehouse-logical',
  'warehouse-create',
  'warehouse-edit',
  'warehouse-detail',
  'base-supplier',
  'base-supplier-create',
  'base-supplier-edit',
  'base-supplier-detail',
  'base-customer',
  'base-customer-create',
  'base-customer-edit',
  'base-customer-detail',
  'base-product',
  'base-product-create',
  'base-product-edit',
  'base-product-detail',
  'base-logistics-carrier',
  'base-logistics-carrier-detail',
  'base-logistics-product',
  'base-auxiliary',
  'purchase-order',
  'purchase-order-create',
  'purchase-order-edit',
  'purchase-order-detail',
  'purchase-receipt-notice',
  'purchase-receipt-notice-create',
  'purchase-receipt-notice-edit',
  'purchase-receipt-notice-detail',
  'purchase-inbound',
  'purchase-inbound-detail',
  'sales-order',
  'sales-order-create',
  'sales-order-edit',
  'sales-order-detail',
  'sales-delivery-notice',
  'sales-delivery-notice-create',
  'sales-delivery-notice-edit',
  'sales-delivery-notice-detail',
  'sales-outbound',
  'sales-outbound-detail',
  'purchase-return',
  'purchase-return-create',
  'purchase-return-edit',
  'purchase-return-detail',
  'purchase-return-notice',
  'purchase-return-notice-create',
  'purchase-return-notice-edit',
  'purchase-return-notice-detail',
  'purchase-return-outbound',
  'purchase-return-outbound-detail',
  'sales-return',
  'sales-return-create',
  'sales-return-edit',
  'sales-return-detail',
  'sales-return-notice',
  'sales-return-notice-create',
  'sales-return-notice-edit',
  'sales-return-notice-detail',
  'sales-return-inbound',
  'sales-return-inbound-detail',
  'import-center',
  'export-center',
  'notification-center',
  'profile',
  'inventory-stock-query',
  'inventory-stock-flow',
  'inventory-compare',
  'inventory-other-inbound-request',
  'inventory-other-inbound-request-create',
  'inventory-other-inbound-request-edit',
  'inventory-other-inbound-request-detail',
  'inventory-other-inbound',
  'inventory-other-inbound-detail',
  'inventory-other-outbound-request',
  'inventory-other-outbound-request-create',
  'inventory-other-outbound-request-edit',
  'inventory-other-outbound-request-detail',
  'inventory-other-outbound',
  'inventory-other-outbound-detail',
  'inventory-transfer-order',
  'inventory-transfer-order-create',
  'inventory-transfer-order-edit',
  'inventory-transfer-order-detail',
  'inventory-transfer-out-notice',
  'inventory-transfer-out-notice-detail',
  'inventory-transfer-in-notice',
  'inventory-transfer-in-notice-detail',
  'inventory-direct-transfer',
  'inventory-direct-transfer-create',
  'inventory-direct-transfer-edit',
  'inventory-direct-transfer-detail',
  'price-purchase-list',
  'price-sales-list',
  'price-purchase-adjust',
  'price-purchase-adjust-create',
  'price-purchase-adjust-edit',
  'price-purchase-adjust-detail',
  'price-sales-adjust',
  'price-sales-adjust-create',
  'price-sales-adjust-edit',
  'price-sales-adjust-detail',
]);

export function isPageImplemented(pageId) {
  // 工作台一期后置，侧栏仍保留演示入口。
  if (pageId === 'home') return true;
  return IMPLEMENTED_PAGE_IDS.has(pageId);
}

export function isNavModuleAccessible(navItem) {
  if (navItem.id === 'home') return true;
  return navItem.groups?.some((group) => group.items.some((item) => isPageImplemented(item.pageId))) ?? false;
}
