/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          'Microsoft YaHei',
          'PingFang SC',
          'Hiragino Sans GB',
          'Helvetica Neue',
          'Arial',
          'sans-serif',
        ],
      },
      fontSize: {
        'erp-compact': ['12px', { lineHeight: '20px' }],
        'erp-comfortable': ['14px', { lineHeight: '20px' }],
        'erp-caption': ['11px', { lineHeight: '16px' }],
        'erp-tab': ['13px', { lineHeight: '20px' }],
        'erp-section-title': ['14px', { lineHeight: '20px' }],
        'erp-emphasis': ['15px', { lineHeight: '22px' }],
        'erp-doc-title': ['17px', { lineHeight: '24px' }],
        'erp-page-title': ['18px', { lineHeight: '24px' }],
      },
      colors: {
        erp: {
          primary: 'rgb(var(--erp-brand-500) / <alpha-value>)',
          'primary-hover': 'rgb(var(--erp-brand-600) / <alpha-value>)',
          'primary-soft': 'rgb(var(--erp-brand-50) / <alpha-value>)',
          text: 'rgb(var(--erp-text-primary) / <alpha-value>)',
          'text-title': 'rgb(var(--erp-text-title) / <alpha-value>)',
          'text-section': 'rgb(var(--erp-text-section) / <alpha-value>)',
          'text-muted': 'rgb(var(--erp-text-secondary) / <alpha-value>)',
          'text-subtle': 'rgb(var(--erp-text-tertiary) / <alpha-value>)',
          placeholder: 'rgb(var(--erp-text-placeholder) / <alpha-value>)',
          surface: 'rgb(var(--erp-surface-canvas) / <alpha-value>)',
          'surface-header': 'rgb(var(--erp-surface-header) / <alpha-value>)',
          'surface-panel': 'rgb(var(--erp-surface-panel) / <alpha-value>)',
          'surface-muted': 'rgb(var(--erp-surface-muted) / <alpha-value>)',
          'surface-table-head': 'rgb(var(--erp-surface-table-head) / <alpha-value>)',
          'surface-table-zebra': 'rgb(var(--erp-surface-table-zebra) / <alpha-value>)',
          'surface-hover': 'rgb(var(--erp-surface-hover) / <alpha-value>)',
          'surface-selected': 'rgb(var(--erp-surface-selected) / <alpha-value>)',
          'surface-disabled': 'rgb(var(--erp-surface-disabled) / <alpha-value>)',
          overlay: 'rgb(var(--erp-overlay) / <alpha-value>)',
          border: 'rgb(var(--erp-border-default) / <alpha-value>)',
          'border-light': 'rgb(var(--erp-border-subtle) / <alpha-value>)',
          'border-card': 'rgb(var(--erp-border-card) / <alpha-value>)',
          'border-header': 'rgb(var(--erp-border-header) / <alpha-value>)',
          'border-control': 'rgb(var(--erp-border-control) / <alpha-value>)',
          'border-strong': 'rgb(var(--erp-border-strong) / <alpha-value>)',
          'border-table-header': 'rgb(var(--erp-border-table-header) / <alpha-value>)',
          'border-table-row': 'rgb(var(--erp-border-table-row) / <alpha-value>)',
          'border-table-column': 'rgb(var(--erp-border-table-column) / <alpha-value>)',
          warning: 'rgb(var(--erp-warning) / <alpha-value>)',
          'warning-bg': 'rgb(var(--erp-warning-soft) / <alpha-value>)',
          success: 'rgb(var(--erp-success) / <alpha-value>)',
          'success-hover': 'rgb(var(--erp-success-hover) / <alpha-value>)',
          'success-bg': 'rgb(var(--erp-success-soft) / <alpha-value>)',
          info: 'rgb(var(--erp-info) / <alpha-value>)',
          pending: 'rgb(var(--erp-warning) / <alpha-value>)',
          danger: 'rgb(var(--erp-danger) / <alpha-value>)',
          'danger-hover': 'rgb(var(--erp-danger-hover) / <alpha-value>)',
          'danger-bg': 'rgb(var(--erp-danger-soft) / <alpha-value>)',
          'info-bg': 'rgb(var(--erp-info-soft) / <alpha-value>)',
          'sidebar-text': 'rgb(var(--erp-sidebar-text) / <alpha-value>)',
          'sidebar-icon': 'rgb(var(--erp-sidebar-icon) / <alpha-value>)',
          'sidebar-active-bg': 'rgb(var(--erp-sidebar-active-bg) / <alpha-value>)',
          'sidebar-active-text': 'rgb(var(--erp-sidebar-active-text) / <alpha-value>)',
          'sidebar-hover-bg': 'rgb(var(--erp-sidebar-hover-bg) / <alpha-value>)',
          'sidebar-border': 'rgb(var(--erp-sidebar-border) / <alpha-value>)',
          'sidebar-brand': 'rgb(var(--erp-sidebar-brand) / <alpha-value>)',
          'sidebar-surface': 'rgb(var(--erp-sidebar-surface) / <alpha-value>)',
          'sidebar-flyout-border': 'rgb(var(--erp-sidebar-flyout-border) / <alpha-value>)',
          'sidebar-flyout-hover': 'rgb(var(--erp-sidebar-flyout-hover) / <alpha-value>)',
          'sidebar-flyout-text': 'rgb(var(--erp-sidebar-flyout-text) / <alpha-value>)',
          'sidebar-flyout-muted': 'rgb(var(--erp-sidebar-flyout-muted) / <alpha-value>)',
        },
      },
      borderRadius: {
        'erp-control': 'var(--erp-radius-control)',
        'erp-section': 'var(--erp-radius-section)',
        'erp-overlay': 'var(--erp-radius-overlay)',
        'erp-dialog': 'var(--erp-radius-dialog)',
        'erp-status': 'var(--erp-radius-status)',
      },
      boxShadow: {
        'erp-overlay': 'var(--erp-shadow-overlay)',
        'erp-dialog': 'var(--erp-shadow-dialog)',
        'erp-flyout': 'var(--erp-shadow-flyout)',
      },
    },
  },
  plugins: [],
};
